blank_issues_enabled: true
contact_links:
  - name: Request Components
    url: https://github.com/LumexUI/lumexui/discussions/categories/component-requests
    about: 🧩 Suggest new components you'd like to see added to LumexUI.
  - name: Get Help
    url: https://github.com/LumexUI/lumexui/discussions/new?category=help
    about: 🙏 If you can't get something to work the way you expect, ask for help in our discussion forums.
  - name: Discord Community
    url: https://discord.com/invite/6BVRhjyTcX
    about: 💬 Ask quick questions or simply chat on the LumexUI community Discord server.
