name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
      - 'tests/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --no-restore --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
